

def console_ignore_exception(func):
    pass